### ISSUE TITLE
MDS

### ISSUE THREAD

**Issue by jjcruzmotta** [edlinguerra/LENFEST#1]
Hola Edlin...puedes hacer un nMDS por region donde no se muestre las localidades....es basicamente una sola linea donde cada punto es el centroide para toda la region.

**Comment by jjcruzmotta** [comment]
Tambien chamo...no se si pueda hacer tambien para los datos SEAMAP.

**Comment by edlinguerra** [comment]
justo estoy con lo del nMDS para Puerto Rico considerando sus 7 regiones. Acabo de terminar de escribir una función para que sea aun más rápido generar los nMDS a cualquier set de datos biológicos. Estos que vistes fueron creados con códigos automáticos pero había que correrlos para cada set de datos. Ahora solo debo indicar qué tipo de datos, resolución espacial y listo. Es decir, se puede correr para SEAMAP muy rápido, pero primero voy a escribir la función para los shade-plot. cuando esté listo te aviso

**Comment by jjcruzmotta** [comment]
Muchas gracias Edlin.

**Comment by jjcruzmotta** [comment]
Chamo...a medida que trabajo se me van ocurriendo cosas, pero no quiero sonar ladilla...por favor discúlpame.
Pero quería saber si además de los MDS se pudiesen hacer los equivalentes métricos (mMDS o PCO) con los vectores e la variables (> 70% correlación).

Saludos

JJ

**Comment by edlinguerra** [comment]
Chamo, solo pude hacer los MDS centroides para las regiones de PR, a los tres tipos de datos. Tuve muchas interrupciones en el día, fue ahora en la tarde/noche que pude dedicar a escribir los códigos de los shade plot (por cierto, que maravilla el matrix display, que peo hacer esa verga en R), y a correr los MDS de centroides para datos SEAMAP, pero no he podido terminar los códigos y ya estoy viendo triple.  No podré retomar esto sino hasta la tarde, también veré qué tipo de códigos requiero para automatizar los mMDS con vectores de variables ambientales. Te mantengo al tanto

**Comment by jjcruzmotta** [comment]
Hola Edlin....no pasa nada brother. Ya me communiqué con la gente para atrasar el deadline y tenemos hasta el 28.  
Por lo de los MDS de region...lo que te estaba pidiendo era solamente el centroide por region por separado. Es decir, una sola linea por MDS. Por ejemplo el MDS region oeste tiene tres localidades ...la idea seria producir un MDS que tenga una sola linea.
Como ves el dia de hoy para trabjar en esto y las otras cosas?

JJ

**Comment by edlinguerra** [comment]
Ya están los MDS anuales para cada región. También están los PCO ya que hay varios degenarate solutions. Los shadeplot están en todos los casos. Repetí todos los MDS por sitios-año, localidad-año y regio-año. Todos son análisis para PRCRMP, ahora voy a generar los de SEAMAP. También están los datos en cada caso, por si quieres hacer una inspección desde PRIMER. El formato de cada archivo es .csv, los datos ya tiene transformación (el nombre del archivo dice el tipo), y la columna para generar factores está lista, pero se le debe quitar manualmente un guion del encabezado.

**Comment by edlinguerra** [comment]
Acabo de subir trayectorias anuales (PCO, MDS y shadeplot) para cada region (East, West) en datos PR de SEAMAP

**Comment by edlinguerra** [comment]
todos los datos (ambientales, landing) están en su escala original ya en formato PRIMER (archivos Excel)
